language: go

go:
 - 1.10.x
 - master

matrix:
  fast_finish: true
  allow_failures:
    - go: master

before_install:
  - go get github.com/mattn/goveralls
script:
  - $HOME/gopath/bin/goveralls -v -service=travis-ci